---
# Configuration file for running ChIP-seq workflow

# Here is where the reference genomes are specified
reference:
    # name of the genome
    U00096.3:
        # location of the genbanks. If put in the location and format shown
        # below the pipeline will attempt to pull this file from NCBI by
        # accession number. Each genbank MUST have a associated name which
        # is used to name the contig pulled from it.
        genbanks: 
            U00096.3: resources/genbanks/U00096.3.gbk
        # This is the fasta file for each chromosome in the genome
        # If specified location then it is automatically parsed
        # from the genbank.
        fastas:
            - results/alignment/process_genbank/U00096.3/U00096.3.fna

    AL009126.3:
        # location of the genbanks. If put in the location and format shown
        # below the pipeline will attempt to pull this file from NCBI by
        # accession number. Each genbank MUST have a associated name which
        # is used to name the contig pulled from it.
        genbanks: 
            AL009126.3: resources/genbanks/AL009126.3.gbk
        # This is the fasta file for each chromosome in the genome
        # If specified location then it is automatically parsed
        # from the genbank.
        fastas:
            - results/alignment/process_genbank/AL009126.3/AL009126.3.fna

# Options to control preprocessing rules
preprocessing:
    # GENERAL PARADIGM FOR CONTROLLING THINGS FOR ALL SAMPLES OR SPECIFICALLY
    # FOR EACH SAMPLE INDIVIDUALLY
    # Example: 
    # Control the parameter string passed to cutadapt. Here you could change
    # the adaptor sequences for every sample by using 
    # cut_param_string:
    #   value: "my string here"
    # or by sample by using :
    # cut_param_string: 
    #   column: cutadapt_params
    # and specifying the name of the column in the
    # sample sheet that holds the strings you want to for each sample. In this
    # example it would be the column cutadapt_params that holds a string for
    # each sample.
    #
    # This same paradigm is used for all option that have a value or column
    # specifier
    cutadapt_pe:
        cut_param_string:
            value: "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
    # Control the parameter string from trimmomatic
    trimmomatic_pe:
        trim_param_string:
            value: "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15"

# Options to control alignment rules
alignment:
    process_genbank:
        # Control what features are parsed from the genbank when pulling out
        # bed files
        features:
            value: "CDS tRNA rRNA ncRNA"
        qual_name: 
            value: "gene locus_tag"

    bowtie2_map:
        # controls how bowtie2 does its alignments
        bowtie2_param_string:
            value: "--end-to-end --very-sensitive --phred33"
        # controls samtools filtering as reads come out of bowtie2. Default
        # is to just convert the sam records into a bam with -b
        samtools_view_param_string:
            value: "-b"

    bowtie2_map_se:
        # controls how bowtie2 does its alignments for single end data
        bowtie2_param_string:
            value: "--end-to-end --very-sensitive --phred33"
        # controls samtools filtering as reads come out of bowtie2. Default
        # is to just convert the sam records into a bam with -b
        samtools_view_param_string:
            value: "-b"


# Options to control genome coverage calculations
coverage_and_norm:

    # what resolution in bp do you want the coverage to be calculated?
    # NET-seq should be single bp resolution
    resolution: 1
    # drop NaNs and Infs from zero coverage in input or extracted
    # Note
    # that bigwigs will not display properly in IGV if they have nans or infs
    dropNaNsandInfs: true

    # rule specific controls
    # Each of these can be specified either as a single value for every sample
    # or as a column in the sample_sheet using column: column_name
    deeptools_coverage:
        bamCoverage_param_string:
            # Want only the 5' end of the read (which is really the
            # 3' end of the NET-seq read)
            value: "--Offset 1"

# Options to control quality control
quality_control:
    # what column to group samples by for ChIP-QC output plots?
    group_by: genome

# Options to control variant calling. I.e. running breseq on the input samples
variant_calling:
    # Which samples do you want to run variant calling on. Typically
    # only the input samples as specified by having no sample name in
    # the "input_sample" column
    filter: "input_sample.isnull() or not input_sample.isnull()"
    # Which reference to compare against. Reference must be defined above
    # in the reference section. Can specify a single value for all samples
    # or a column in the metadata sheet to define a reference for each
    # sample
    reference:
        column: "genome"


NETseq:
    pause_calling:
        poisson_gw:
            model_type: "Genomewide"
            wsize: 100
            NETseq_pause_params: "--method Poisson --alpha 0.05 --filter avg_cov cov --cov_cutoff 1 --avg_cov_cutoff 1"
        larson_gw:
            model_type: "Genomewide"
            wsize: 100
            NETseq_pause_params: "--method Larson --alpha 0.05 --filter avg_cov cov --cov_cutoff 1 --avg_cov_cutoff 1"
        bootstrap_gw:
            model_type: "Genomewide"
            wsize: 100
            NETseq_pause_params: "--method bootstrap --alpha 0.05 --filter avg_cov cov --cov_cutoff 1 --avg_cov_cutoff 1"
        # Negative binomial doesn't seem to call any pauses
        negBinom_gw:
            model_type: "Genomewide"
            wsize: 100
            # changed alpha to 1 to see how bad the pvalues were
            NETseq_pause_params: "--method negBinom --alpha 1 --filter avg_cov cov --cov_cutoff 1 --avg_cov_cutoff 1"
        poisson_region:
            model_type: "Region"
            regions: "results/alignment/process_genbank/U00096.3/U00096.3.bed"
            NETseq_pause_params: "--method Poisson --alpha 0.05 "
        larson_region:
            model_type: "Region"
            regions: "results/alignment/process_genbank/U00096.3/U00096.3.bed"
            NETseq_pause_params: "--method Larson --alpha 0.05 "
        bootstrap_region:
            model_type: "Region"
            regions: "results/alignment/process_genbank/U00096.3/U00096.3.bed"
            NETseq_pause_params: "--method bootstrap --alpha 0.05 "
            



# Control for the postprocessing submodule
postprocessing:
    # summarizes values by region
    bwtools_query:
        # Can specify different "models" to run by naming them here
        # Model 1 - look at the full coverage for all genes
        all_genes_plus_cov:
            filter: "genome == 'U00096.3'"
            # which regions to use? Specifying a file like this has the pipeline
            # parse it from your genbank file given the process genbank
            # parameters above in the alignment section
            regions: "results/alignment/process_genbank/U00096.3/U00096.3.bed"
            coord: "relative_start"
            # which files to use? This file signature will substitute in
            # a sample name for the %s
            filesignature: "results/coverage_and_norm/deeptools_coverage/%s_plus_raw.bw"
            # how many bp upstream (5') of a feature to include
            upstream: 200
            # how many bp downstream (3') of a feature to include
            downstream: 0
            # what resolution to query data (shouldn't be lower than the
            # resolution of your file
            res : 1
            # How do you want to summarize your data? (identity gives every data
            # point in tidy format)
            summarize: "identity"

        all_genes_minus_cov:
            filter: "genome == 'U00096.3'"
            # which regions to use? Specifying a file like this has the pipeline
            # parse it from your genbank file given the process genbank
            # parameters above in the alignment section
            regions: "results/alignment/process_genbank/U00096.3/U00096.3.bed"
            # which files to use? This file signature will substitute in
            # a sample name for the %s
            filesignature: "results/coverage_and_norm/deeptools_coverage/%s_minus_raw.bw"
            coord: "relative_start"
            # how many bp upstream (5') of a feature to include
            upstream: 200
            # how many bp downstream (3') of a feature to include
            downstream: 0
            # what resolution to query data (shouldn't be lower than the
            # resolution of your file
            res : 1
            # How do you want to summarize your data? (identity gives every data
            # point in tidy format)
            summarize: "identity"

        bsub_genes_plus_cov:
            filter: "genome == 'AL009126.3'"
            # which regions to use? Specifying a file like this has the pipeline
            # parse it from your genbank file given the process genbank
            # parameters above in the alignment section
            regions: "results/alignment/process_genbank/AL009126.3/AL009126.3.bed"
            # which files to use? This file signature will substitute in
            # a sample name for the %s
            filesignature: "results/coverage_and_norm/deeptools_coverage/%s_plus_raw.bw"
            # how many bp upstream (5') of a feature to include
            upstream: 0
            # how many bp downstream (3') of a feature to include
            downstream: 0
            # what resolution to query data (shouldn't be lower than the
            # resolution of your file
            res : 5
            # How do you want to summarize your data? (identity gives every data
            # point in tidy format)
            summarize: "identity"

        bsub_genes_minus_cov:
            filter: "genome == 'AL009126.3'"
            # which regions to use? Specifying a file like this has the pipeline
            # parse it from your genbank file given the process genbank
            # parameters above in the alignment section
            regions: "results/alignment/process_genbank/AL009126.3/AL009126.3.bed"
            # which files to use? This file signature will substitute in
            # a sample name for the %s
            filesignature: "results/coverage_and_norm/deeptools_coverage/%s_minus_raw.bw"
            # how many bp upstream (5') of a feature to include
            upstream: 0
            # how many bp downstream (3') of a feature to include
            downstream: 0
            # what resolution to query data (shouldn't be lower than the
            # resolution of your file
            res : 5
            # How do you want to summarize your data? (identity gives every data
            # point in tidy format)
            summarize: "identity"
