module_order:
    - fastqc:
        name: 'FastQC (trimmed)'
        anchor: 'fastqc_trimmed'
        info: 'FastQC results after adapter trimming.'
        target: ''
        path_filters:
            - '*/fastqc_processed/*fastqc.zip'
    - trimmomatic
    - cutadapt
    - fastqc:
        name: 'FastQC (raw)'
        info: "FastQC results on the raw files (filenames may differ)"
        anchor: 'fastqc_raw'
        path_filters:
            - '*/fastqc_raw/*fastqc.zip'

report_section_order:
    fastq_trimmed:
        before: fastqc_raw

extra_fn_clean_exts:
    - type: "truncate"
      pattern: "bt2" 
    - type: remove
      pattern: "trim_paired_"
    - type: "truncate"
      pattern: "R1"
      module:
          - trimmomatic
          - cutadapt
    - type: "truncate"
      pattern: "R2"
      module:
          - trimmomatic
          - cutadapt
    - type: "truncate"
      pattern: "cutadapt"
      module:
          - cutadapt
    - type: "truncate"
      pattern: "_cut"
      module:
          - trimmomatic

use_filename_as_sample_name:
    - fastqc
    - cutadapt

plots_flat_numseries: 250
